export const users = [
  {
    id: '1',
    name: 'murilo henrique lemes',
    contract: '2017-01-03',
    server: 'Servidor 1',
    plan: 'Plano A',
    expirationDate: '2020-01-03',
    situation: 'Deve',
    status: 'Inativo',
  },
  {
    id: '2',
    name: 'Murilo',
    contract: '2020-05-10',
    server: 'Servidor 2',
    plan: 'Plano B',
    expirationDate: '2020-12-10',
    situation: 'Deve',
    status: 'Inativo',
  },
  {
    id: '3',
    name: 'Murilo',
    contract: '2020-01-20',
    server: 'Servidor 3',
    plan: 'Plano C',
    expirationDate: '2021-10-10',
    situation: 'Pago',
    status: 'Ativo',
  },
  {
    id: '4',
    name: 'Lemes Murilo',
    contract: '2020-01-20',
    server: 'Servidor 1',
    plan: 'Plano H',
    expirationDate: '2021-10-10',
    situation: 'Pago',
    status: 'Ativo',
  },
  {
    id: '5',
    name: 'Murilo Lemes',
    contract: '2020-01-20',
    server: 'Servidor 1',
    plan: 'Plano A',
    expirationDate: '2021-10-10',
    situation: 'Pago',
    status: 'Ativo',
  },
  {
    id: '6',
    name: 'Henrique Lemes',
    contract: '2020-01-20',
    server: 'Servidor 1',
    plan: 'Plano A',
    expirationDate: '2021-10-10',
    situation: 'Pago',
    status: 'Ativo',
  },
  {
    id: '7',
    name: 'Murilo Henrique Lemes',
    contract: '2020-01-20',
    server: 'Servidor 1',
    plan: 'Plano B',
    expirationDate: '2021-10-10',
    situation: 'Pago',
    status: 'Ativo',
  },
  {
    id: '8',
    name: 'Murilo Henrique',
    contract: '2020-01-20',
    server: 'Servidor 1',
    plan: 'Plano C',
    expirationDate: '2021-10-10',
    situation: 'Pago',
    status: 'Ativo',
  },
  {
    id: '9',
    name: 'Murilo Lemes',
    contract: '2020-01-20',
    server: 'Servidor 5',
    plan: 'Plano A',
    expirationDate: '2021-10-10',
    situation: 'Deve',
    status: 'Inativo',
  },
  {
    id: '10',
    name: 'Henrique Lemes',
    contract: '2020-01-20',
    server: 'Servidor 1',
    plan: 'Plano G',
    expirationDate: '2021-10-10',
    situation: 'Deve',
    status: 'Inativo',
  },
  {
    id: '11',
    name: 'Henrique Murilo',
    contract: '2020-01-20',
    server: 'Servidor 4',
    plan: 'Plano F',
    expirationDate: '2021-10-10',
    situation: 'Pago',
    status: 'Ativo',
  },
  {
    id: '12',
    name: 'Lemes Henrique',
    contract: '2020-01-20',
    server: 'Servidor 10',
    plan: 'Plano D',
    expirationDate: '2021-10-10',
    situation: 'Deve',
    status: 'Inativo',
  },
  {
    id: '13',
    name: 'Murilo Henrique Lemes',
    contract: '2020-01-20',
    server: 'Servidor 7',
    plan: 'Plano C',
    expirationDate: '2021-10-10',
    situation: 'Pago',
    status: 'Ativo',
  },
  {
    id: '14',
    name: 'Murilo Henrique Lemes',
    contract: '2020-01-20',
    server: 'Servidor 6',
    plan: 'Plano H',
    expirationDate: '2021-10-10',
    situation: 'Deve',
    status: 'Inativo',
  },
  {
    id: '15',
    name: 'Murilo Henrique Lemes',
    contract: '2020-01-20',
    server: 'Servidor 8',
    plan: 'Plano A',
    expirationDate: '2021-10-10',
    situation: 'Pago',
    status: 'Ativo',
  },
  {
    id: '16',
    name: 'Murilo Henrique Lemes',
    contract: '2020-01-20',
    server: 'Servidor 9',
    plan: 'Plano G',
    expirationDate: '2021-10-10',
    situation: 'Pago',
    status: 'Ativo',
  },
  {
    id: '17',
    name: 'Murilo Henrique Lemes',
    contract: '2020-01-20',
    server: 'Servidor 6',
    plan: 'Plano D',
    expirationDate: '2021-10-10',
    situation: 'Pago',
    status: 'Ativo',
  },
  {
    id: '18',
    name: 'Murilo Henrique Lemes',
    contract: '2020-01-20',
    server: 'Servidor 6',
    plan: 'Plano D',
    expirationDate: '2021-10-10',
    situation: 'Pago',
    status: 'Ativo',
  },
  {
    id: '19',
    name: 'Murilo Henrique Lemes',
    contract: '2020-01-20',
    server: 'Servidor 6',
    plan: 'Plano D',
    expirationDate: '2021-10-10',
    situation: 'Pago',
    status: 'Ativo',
  },
  {
    id: '20',
    name: 'Murilo Henrique Lemes',
    contract: '2020-01-20',
    server: 'Servidor 6',
    plan: 'Plano D',
    expirationDate: '2021-10-10',
    situation: 'Pago',
    status: 'Ativo',
  },
  {
    id: '21',
    name: 'Murilo Henrique Lemes',
    contract: '2020-01-20',
    server: 'Servidor 6',
    plan: 'Plano D',
    expirationDate: '2021-10-10',
    situation: 'Pago',
    status: 'Ativo',
  },
  {
    id: '22',
    name: 'Murilo Henrique Lemes',
    contract: '2020-01-20',
    server: 'Servidor 6',
    plan: 'Plano D',
    expirationDate: '2021-10-10',
    situation: 'Pago',
    status: 'Ativo',
  },
  {
    id: '23',
    name: 'Murilo Henrique Lemes',
    contract: '2020-01-20',
    server: 'Servidor 6',
    plan: 'Plano D',
    expirationDate: '2021-10-10',
    situation: 'Pago',
    status: 'Ativo',
  },
  {
    id: '24',
    name: 'Murilo Henrique Lemes',
    contract: '2020-01-20',
    server: 'Servidor 6',
    plan: 'Plano D',
    expirationDate: '2021-10-10',
    situation: 'Pago',
    status: 'Ativo',
  },
  {
    id: '25',
    name: 'Murilo Henrique Lemes',
    contract: '2020-01-20',
    server: 'Servidor 6',
    plan: 'Plano D',
    expirationDate: '2021-10-10',
    situation: 'Pago',
    status: 'Ativo',
  },
  {
    id: '26',
    name: 'Murilo Henrique Lemes',
    contract: '2020-01-20',
    server: 'Servidor 6',
    plan: 'Plano D',
    expirationDate: '2021-10-10',
    situation: 'Pago',
    status: 'Ativo',
  },
  {
    id: '27',
    name: 'Murilo Henrique Lemes',
    contract: '2020-01-20',
    server: 'Servidor 6',
    plan: 'Plano D',
    expirationDate: '2021-10-10',
    situation: 'Pago',
    status: 'Ativo',
  },
  {
    id: '28',
    name: 'Murilo Henrique Lemes',
    contract: '2020-01-20',
    server: 'Servidor 6',
    plan: 'Plano D',
    expirationDate: '2021-10-10',
    situation: 'Pago',
    status: 'Ativo',
  },
  {
    id: '29',
    name: 'Murilo Henrique Lemes',
    contract: '2020-01-20',
    server: 'Servidor 6',
    plan: 'Plano D',
    expirationDate: '2021-10-10',
    situation: 'Pago',
    status: 'Ativo',
  },
  {
    id: '30',
    name: 'Murilo Henrique Lemes',
    contract: '2020-01-20',
    server: 'Servidor 6',
    plan: 'Plano D',
    expirationDate: '2021-10-10',
    situation: 'Pago',
    status: 'Ativo',
  },
];

export const filterType = [
  {
    id: '0',
    name: 'Status',
  },
  {
    id: '1',
    name: 'Nome',
  },
  {
    id: '2',
    name: 'Servidor',
  },
  {
    id: '3',
    name: 'Situação',
  },
  {
    id: '4',
    name: 'Data de Contrato',
  },
  {
    id: '5',
    name: 'Data de Vencimento',
  },
];

export const servers = [
  {
    id: 0,
    server: 'Servidor 1',
  },
  {
    id: 1,
    server: 'Servidor 2',
  },
  {
    id: 2,
    server: 'Servidor 3',
  },
  {
    id: 3,
    server: 'Servidor 4',
  },
  {
    id: 4,
    server: 'Servidor 5',
  },
  {
    id: 5,
    server: 'Servidor 6',
  },
  {
    id: 6,
    server: 'Servidor 7',
  },
  {
    id: 7,
    server: 'Servidor 8',
  },
  {
    id: 8,
    server: 'Servidor 9',
  },
  {
    id: 9,
    server: 'Servidor 10',
  },
];
